source 'http://rubygems.org'

gem 'rails',          '3.2.5'
gem 'jquery-rails',   '2.0.2'
gem "haml-rails",     "0.3.4"
gem 'thin',           '1.3.1'
DATABASE_GEM
# gem 'paperclip', '3.0.4'
# gem 'aws-sdk', '1.5.2'
# gem 'paranoia', '1.1.0'
# gem 'omniauth', '1.1.0'
# gem 'omniauth-facebook', '1.3.0'
# gem 'pg', '0.13.0'
# gem 'typus', '3.1.10'
# gem 'kaminari', '0.13.0'
# gem 'rdiscount', '1.6.8'

group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier',     '1.2.3'
end

group :development do
  gem 'heroku',       '2.4.2'
  gem 'rspec-rails',  '2.10.1'
  gem 'integration', :git => 'git://github.com/mergulhao/integration.git'
end

group :test do
  gem 'rspec-rails',        '2.10.1'
  gem 'fakeweb',            '1.3.0'
  gem 'ruby-debug19',       '0.11.6'
  gem 'shoulda-matchers',   '1.1.0'
  gem 'factory_girl_rails', '1.7.0'
  gem 'timecop',            '0.3.5'
  gem 'simplecov', '0.6.1', :require => false
end
