source 'http://rubygems.org'

gem 'rails',          '3.2.3'
gem 'jquery-rails',   '2.0.1'
gem 'haml',           '3.1.4'
gem 'thin',           '1.3.1'
DATABASE_GEM

group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'uglifier',     '~> 1.2.3'
end

group :development do
  gem 'rspec-rails',  '2.10.1'
  gem 'integration', :git => 'git://github.com/mergulhao/integration.git'
end

group :test do
  gem 'rspec-rails',        '2.10.1'
  gem 'fakeweb',            '1.3.0'
  gem 'ruby-debug19',       '0.11.6'
  gem 'shoulda-matchers',   '1.0.0'
  gem 'factory_girl_rails', '1.7.0'
  gem 'valid_attribute',    '1.2.0'
  gem 'timecop',            '0.3.5'
  gem 'simplecov', '0.6.1', :require => false
end
